- Updated LXC templates

diff --git a/salt/root/v1_0/lxc/rainmaker_templates/files/lxc-rainmaker-project-branch b/salt/root/v1_0/lxc/rainmaker_templates/files/lxc-rainmaker-project-branch
--- a/salt/root/v1_0/lxc/rainmaker_templates/files/lxc-rainmaker-project-branch
+++ b/salt/root/v1_0/lxc/rainmaker_templates/files/lxc-rainmaker-project-branch
@@ -24,7 +24,7 @@ install() {
 }
 
 # Set up the path option
-options=$(getopt -o n:p: -l path:,name:,rootfs:,profile:,version:,downloadhost:,quiet,debug -- "$@")
+options=$(getopt -o n:p: -l path:,name:,rootfs:,profile:,version:,quiet,debug -- "$@")
 
 if [ $? -ne 0 ]; then
     exit 1
@@ -35,12 +35,7 @@ eval set -- "$options"
 quiet=0
 debug=0
 
-lxc_cache_base="/var/cache/lxc/rainmaker/project"
-
-profile_download_host="http://image.rainmaker-dev.com"
-if [ -n "$RMK_DOWNLOAD_HOST" ]; then
-    profile_download_host="$RMK_DOWNLOAD_HOST"
-fi
+lxc_cache_base="/var/cache/lxc/rainmaker/branch"
 
 # Fetch command line parameters
 while true; do
@@ -50,7 +45,6 @@ while true; do
         --rootfs)       rootfs=$2; shift 2;;
         --profile)      profile=$2; shift 2;;
         --version)      version=$2; shift 2;;
-        --downloadhost) profile_download_host=$2; shift 2;;
         --quiet)        quiet=1; shift 1;;
         --debug)        debug=1; shift 1;;
         --)             shift 1; break ;;
@@ -64,11 +58,11 @@ if [ -z "$path" ]; then
 fi
 
 if [ -z "$profile" ]; then
-    profile="rainmaker/default-branch"
+    echo "'profile' parameter is required"
 fi
 
 if [ -z "$version" ]; then
-    version="latest"
+    echo "'version' parameter is required"
 fi
 
 if [ "$(id -u)" != "0" ]; then
@@ -94,46 +88,16 @@ if [ "$quiet" -ne 1 ]; then
     echo "Version: $version"
 fi
 
-profile_present=0
-if [ "$version" == "latest" ]; then
-    if [ "`rprofmgr profile:present $profile | fgrep -i 'Profile present'`" != "" ]; then
-        profile_present=1
-    fi
-else
-    if [ "`rprofmgr profile:present $profile --profile-version=$version | fgrep -i 'Profile present'`" != "" ]; then
-        profile_present=1
-    fi
-fi
+major=`echo $version | cut -d'.' -f1`
+lxc_cache_path="$lxc_cache_base/$profile/$major/$version.tgz"
 
-if [ "$profile_present" -ne 1 ]; then
-  echo "Profile is not installed"
-else
-    if [ "$quiet" -ne 1 ]; then
-        echo "Profile is installed"
-    fi
-fi
-
-# Download rootfs
-lxc_cache_path_cmd="rprofmgr profile:version-cache-path $profile"
-if [ "$version" != "latest" ]; then
-    lxc_cache_path_cmd="$lxc_cache_path_cmd --profile-version=$version"
-fi
-lxc_cache_path=$($lxc_cache_path_cmd)
-
-if [ "$lxc_cache_path" == "" ]; then
-    profile_download_cmd="rprofmgr profile:download-version $profile"
-    if [ "$version" != "latest" ]; then
-        profile_download_cmd="$profile_download_cmd --profile-version=$version"
-    fi
-    if [ "$profile_download_host" != "" ]; then
-        profile_download_cmd="$profile_download_cmd --download-host=$profile_download_host"
-    fi
-    $profile_download_cmd
-    lxc_cache_path=$($lxc_cache_path_cmd)
-fi
-
-if [ "$debug" -eq 1 ]; then
+if [ "$quiet" -eq 1 ]; then
     echo "LXC Cache Path: $lxc_cache_path"
+fi
+
+if [ ! -f "$lxc_cache_path" ]; then
+    echo "Profile root filesystem archive is not present in cache"
+    exit 1
 fi
 
 install $lxc_cache_path $rootfs $quiet $debug
